vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone        = "eu=west=3b"
env_prefix        = "dev"
my_ip = "0.0.0.0/0"

instance_type = "t2.micro"
var.public_key_location = "~/.ssh/server.pub"
var.private_key_location = "~/.ssh/server"
image_name = "amzn2-ami-hvm-*-x86_64-gp2" 
